import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";
import AutoImport from "astro-auto-import";
import gtm from "astro-gtm-lite";
import llms from "astro-llms-md";
import { defineConfig, fontProviders, sharpImageService } from "astro/config";
import config from "./src/config/config.json";
import theme from "./src/config/theme.json";
import { translationGaps } from "./src/i18n/contentLocales.ts";

// Helper to parse font string format: "FontName:wght@400;500;600;700"
function parseFontString(fontStr) {
  const [name, weightPart] = fontStr.split(":");
  let weights = [400]; // default weight

  if (weightPart) {
    // Extract weights from wght@400;500;600 format
    const weightMatch = weightPart.match(/wght@?([\d;]+)/);
    if (weightMatch) {
      weights = weightMatch[1].split(";").map((w) => parseInt(w, 10));
    }
  }

  // remove + from font name and add space
  const cleanName = name.replace(/\+/g, " ");
  return { name: cleanName, weights };
}

// Build fonts configuration from theme.json
const fontsConfig = Object.entries(theme.fonts.font_family)
  .filter(([key]) => !key.includes("_type")) // Filter out type entries
  .map(([key, fontStr]) => {
    const { name, weights } = parseFontString(fontStr);
    const typeKey = `${key}_type`;
    const fallback = theme.fonts.font_family[typeKey] || "sans-serif";

    return {
      name,
      cssVariable: `--font-${key}`,
      provider: fontProviders.google(),
      weights,
      display: "swap",
      fallbacks: [fallback],
    };
  });

// Build/dev-time translation-gap report. Report-only: never fails the build
// (the EN-superset orphan check lives in the helper throw + parity test).
// Logs, per collection, EN slugs missing in each non-default locale plus any
// "started but untranslated" (needs_translation: true) entries.
function translationGapReport() {
  return {
    name: "i18n-translation-gap-report",
    hooks: {
      "astro:config:setup": ({ logger }) => {
        const gaps = translationGaps();
        const log = logger.fork("i18n");
        for (const { collection, missing, started } of gaps) {
          for (const [lang, slugs] of Object.entries(missing)) {
            const label = `${collection} (${lang}) missing`;
            log.info(`${label}: ${slugs.length ? slugs.join(", ") : "(none)"}`);
          }
          for (const [lang, slugs] of Object.entries(started)) {
            if (slugs.length) {
              log.warn(
                `${collection} (${lang}) started, untranslated: ${slugs.join(
                  ", ",
                )}`,
              );
            }
          }
        }
      },
    },
  };
}

// https://astro.build/config
export default defineConfig({
  site: config.site.base_url ? config.site.base_url : "http://examplesite.com",
  base: config.site.base_path ? config.site.base_path : "/",
  trailingSlash: config.site.trailing_slash ? "always" : "never",

  // EN default (unprefixed), DE under /de. See src/i18n.
  // `fallback` (rewrite) is a last-resort safety net: any /de/... route NOT
  // generated by our helpers degrades to the EN page output instead of 404.
  // Primary missing-translation UX (notice + canonical) comes from the helper.
  i18n: {
    defaultLocale: "en",
    locales: ["en", "de"],
    routing: { prefixDefaultLocale: false, fallbackType: "rewrite" },
    fallback: { de: "en" },
  },

  vite: { plugins: [tailwindcss()] },
  image: { service: sharpImageService() },
  fonts: fontsConfig,
  integrations: [
    translationGapReport(),
    react(),
    sitemap({
      i18n: {
        defaultLocale: "en",
        locales: { en: "en", de: "de" },
      },
    }),

    AutoImport({
      imports: [
        "@/shortcodes/Button",
        "@/shortcodes/Accordion",
        "@/shortcodes/Notice",
        "@/shortcodes/Tldr",
        "@/shortcodes/Video",
        "@/shortcodes/Youtube",
        "@/shortcodes/Tabs",
        "@/shortcodes/Tab",
      ],
    }),
    mdx(),
    gtm({
      enable: config.google_tag_manager.enable,
      id: config.google_tag_manager.gtm_id,
    }),
    llms(),
  ],
  markdown: {
    shikiConfig: {
      theme: "one-dark-pro",
      wrap: true,
    },
  },
});
